#!/usr/bin/env python

import requests
import json

bitcoin_api_url = 'https://api.coinmarketcap.com/v1/ticker/'
r = requests.get(bitcoin_api_url)
report = r.json()
json_encoded = json.dumps(report)
print(json_encoded)
